# default: global configuration to be applied to all repos
# repos: list of repos with specific configuration to be applied in addition to default
#   labels: list of labels - keys for each item: color, description, name, target, deleteAfter, previously
#     deleteAfter: 2006-01-02T15:04:05Z (rfc3339)
#     previously: list of previous labels (color name deleteAfter, previously)
#     target: one of issues, prs, or both (also TBD)
#     addedBy: human? prow plugin? other?
---
default:
  labels:
    - color: 0ffa16
      description: Indicates a PR has been approved by an approver from all required OWNERS files.
      name: approved
      target: prs
      prowPlugin: approve
      addedBy: approvers
    - color: fef2c0
      description: Indicates a cherry-pick PR into a release branch has been approved by the release branch manager. # Consumed by the kubernetes/kubernetes cherry-pick-queue.
      name: cherry-pick-approved
      target: prs
      addedBy: humans
      previously:
        - name: cherrypick-approved
    - color: e11d21
      description: Indicates that a PR should not merge because it touches files in blocked paths.
      name: do-not-merge/blocked-paths
      target: prs
      prowPlugin: blockade
      addedBy: prow
    - color: e11d21
      description: Indicates that a PR is not yet approved to merge into a release branch.
      name: do-not-merge/cherry-pick-not-approved
      target: prs
      addedBy: prow
      prowPlugin: cherrypickunapproved
    - color: e11d21
      description: Indicates that a PR should not merge because someone has issued a /hold command.
      name: do-not-merge/hold
      target: prs
      prowPlugin: hold
      addedBy: anyone
    - color: e11d21
      description: Indicates that a PR should not merge because it has an invalid commit message.
      name: do-not-merge/invalid-commit-message
      target: prs
      prowPlugin: invalidcommitmsg
      addedBy: prow
    - color: e11d21
      description: Indicates that a PR should not merge because it has an invalid OWNERS file in it.
      name: do-not-merge/invalid-owners-file
      target: prs
      prowPlugin: verify-owners
      addedBy: prow
    - color: e11d21
      description: Indicates that a PR should not merge because it's missing one of the release note labels.
      name: do-not-merge/release-note-label-needed
      previously:
        - name: release-note-label-needed
      target: prs
      prowPlugin: releasenote
      addedBy: prow
    - color: e11d21
      description: Indicates that a PR should not merge because it is a work in progress.
      name: do-not-merge/work-in-progress
      target: prs
      prowPlugin: wip
      addedBy: prow
    - color: 7057ff
      description: Denotes an issue ready for a new contributor, according to the "help wanted" guidelines.
      name: 'good first issue'
      previously:
        - name: for-new-contributors
      target: issues
      prowPlugin: help
      addedBy: anyone
    - color: 006b75
      description: Denotes an issue that needs help from a contributor. Must meet "help wanted" guidelines.
      name: 'help wanted'
      previously:
        - name: help-wanted
      target: issues
      prowPlugin: help
      addedBy: anyone
    - color: e11d21
      description: Categorizes issue or PR as related to adding, removing, or otherwise changing an API
      name: kind/api-change
      previously:
        - name: kind/new-api
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: e11d21
      description: Categorizes issue or PR as related to a bug.
      name: kind/bug
      previously:
        - name: bug
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: c7def8
      description: Categorizes issue or PR as related to cleaning up code, process, or technical debt.
      name: kind/cleanup
      previously:
        - name: kind/friction
        - name: kind/technical-debt
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: c7def8
      description: Categorizes issue or PR as related to design.
      name: kind/design
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: c7def8
      description: Categorizes issue or PR as related to documentation.
      name: kind/documentation
      previously:
        - name: kind/old-docs
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: e11d21
      description: Categorizes issue or PR as related to a consistently or frequently failing test.
      name: kind/failing-test
      previously:
        - name: priority/failing-test
        - name: kind/e2e-test-failure
        - name: kind/upgrade-test-failure
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: c7def8
      description: Categorizes issue or PR as related to CI or testing.
      name: kind/ci
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: c7def8
      description: Categorizes issue or PR as related to a new feature.
      name: kind/feature
      previously:
        - name: enhancement
        - name: kind/enhancement
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: f7c6c7
      description: Categorizes issue or PR as related to a flaky test.
      name: kind/flake
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: 15dd18
      description: Indicates that a PR is ready to be merged.
      name: lgtm
      target: prs
      prowPlugin: lgtm
      addedBy: reviewers or members
    - color: b60205
      description: Indicates a PR that requires an org member to verify it is safe to test. # This is to prevent spam/abuse of our CI system, and can be circumvented by becoming an org member. Org members can remove this label with the `/ok-to-test` command.
      name: needs-ok-to-test
      target: prs
      prowPlugin: trigger
      addedBy: prow
    - color: 15dd18
      description: Indicates a non-member PR verified by an org member that is safe to test. # This is the opposite of needs-ok-to-test and should be mutually exclusive.
      name: ok-to-test
      target: prs
      prowPlugin: trigger
      addedBy: prow
    - color: fef2c0
      description: Lowest priority. Possibly useful, but not yet enough support to actually get it done. # These are mostly place-holders for potentially good ideas, so that they don't get completely forgotten, and can be referenced /deduped every time they come up.
      name: priority/awaiting-more-evidence
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: fbca04
      description: Higher priority than priority/awaiting-more-evidence. # There appears to be general agreement that this would be good to have, but we may not have anyone available to work on it right now or in the immediate future. Community contributions would be most welcome in the mean time (although it might take a while to get them reviewed if reviewers are fully occupied with higher priority issues, for example immediately before a release).
      name: priority/backlog
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: e11d21
      description: Highest priority. Must be actively worked on as someone's top priority right now. # Stuff is burning. If it's not being actively worked on, someone is expected to drop what they're doing immediately to work on it. Team leaders are responsible for making sure that all the issues, labeled with this priority, in their area are being actively worked on. Examples include user-visible bugs in core features, broken builds or tests and critical security issues.
      name: priority/critical-urgent
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: eb6420
      description: Important over the long term, but may not be staffed and/or may need multiple releases to complete.
      name: priority/important-longterm
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: eb6420
      description: Must be staffed and worked on either currently, or very soon, ideally in time for the next release.
      name: priority/important-soon
      target: both
      prowPlugin: label
      addedBy: anyone
    - color: c2e0c6
      description: Denotes a PR that will be considered when it comes time to generate release notes.
      name: release-note
      target: prs
      prowPlugin: releasenote
      addedBy: prow
    - color: c2e0c6
      description: Denotes a PR that introduces potentially breaking changes that require user action. # These actions will be specifically called out when it comes time to generate release notes.
      name: release-note-action-required
      target: prs
      prowPlugin: releasenote
      addedBy: prow
    - color: c2e0c6
      description: Denotes a PR that doesn't merit a release note. # will be ignored when it comes time to generate release notes.
      name: release-note-none
      target: prs
      prowPlugin: releasenote
      addedBy: prow or member or author
    - color: ee9900
      description: Denotes a PR that changes 100-499 lines, ignoring generated files.
      name: size/L
      target: prs
      prowPlugin: size
      addedBy: prow
    - color: eebb00
      description: Denotes a PR that changes 30-99 lines, ignoring generated files.
      name: size/M
      target: prs
      prowPlugin: size
      addedBy: prow
    - color: 77bb00
      description: Denotes a PR that changes 10-29 lines, ignoring generated files.
      name: size/S
      target: prs
      prowPlugin: size
      addedBy: prow
    - color: ee5500
      description: Denotes a PR that changes 500-999 lines, ignoring generated files.
      name: size/XL
      target: prs
      prowPlugin: size
      addedBy: prow
    - color: "009900"
      description: Denotes a PR that changes 0-9 lines, ignoring generated files.
      name: size/XS
      target: prs
      prowPlugin: size
      addedBy: prow
    - color: ee0000
      description: Denotes a PR that changes 1000+ lines, ignoring generated files.
      name: size/XXL
      target: prs
      prowPlugin: size
      addedBy: prow
    - color: ffaa00
      description: Denotes a PR that should be squashed by tide when it merges.
      name: tide/merge-method-squash
      target: prs
      addedBy: humans
      previously:
        - name: tide/squash
    - color: ffaa00
      description: Denotes a PR that should be rebased by tide when it merges.
      name: tide/merge-method-rebase
      target: prs
      addedBy: humans
    - color: ffaa00
      description: Denotes a PR that should use a standard merge by tide when it merges.
      name: tide/merge-method-merge
      target: prs
      addedBy: humans
    - color: e11d21
      description: Denotes an issue that blocks the tide merge queue for a branch while it is open.
      name: tide/merge-blocker
      target: issues
      addedBy: humans
      previously:
        - name: merge-blocker
    - color: f9d0c4
      description: ¯\\\_(ツ)_/¯
      name: "¯\\_(ツ)_/¯"
      target: both
      prowPlugin: shrug
      addedBy: humans
    - color: "795548"
      description: Denotes an issue or PR has remained open with no activity and has become stale.
      name: lifecycle/stale
      target: both
      prowPlugin: lifecycle
    - color: 8fc951
      description: Indicates that an issue or PR is actively being worked on by a contributor.
      name: lifecycle/active
      previously:
        - name: active
      target: both
      prowPlugin: lifecycle
      addedBy: anyone
    - color: d3e2f0
      description: Indicates that an issue or PR should not be auto-closed due to staleness.
      name: lifecycle/frozen
      target: both
      prowPlugin: lifecycle
      addedBy: anyone
    - color: e11d21
      description: Indicates that a PR cannot be merged because it has merge conflicts with HEAD.
      name: needs-rebase
      target: prs
      prowPlugin: needs-rebase
      isExternalPlugin: true
      addedBy: prow
    - color: ff00ff
      description: Indicates an issue lacks a `triage/foo` label and requires one.
      name: needs-triage
      target: issues
      prowPlugin: require-matching-label
      addedBy: prow
    - color: 8fc951
      description: Indicates an issue is ready to be actively worked on.
      name: triage/accepted
      target: issues
      prowPlugin: label
      addedBy: org members
    - color: d455d0
      description: Indicates an issue is a duplicate of other open issue.
      name: triage/duplicate
      target: issues
      addedBy: anyone
    - color: d455d0
      description: Indicates an issue needs more information in order to work on it.
      name: triage/needs-information
      target: issues
      addedBy: anyone
    - color: d455d0
      description: Indicates an issue can not be reproduced as described.
      name: triage/not-reproducible
      target: issues
      addedBy: anyone
    - color: d455d0
      description: Indicates an issue that can not or will not be resolved.
      name: triage/unresolved
      target: issues
      addedBy: anyone