plugins:
  metal3-io:
  - approve
  - assign
  - cat
  - dog
  - heart
  - help
  - hold
  - label
  - lgtm
  - lifecycle
  - pony
  - retitle
  - shrug
  - size
  - trigger
  - verify-owners
  - wip
  - yuks
  metal3-io/baremetal-operator:
  metal3-io/base-image:
  metal3-io/cluster-api-provider-baremetal:
  metal3-io/cluster-api-provider-metal3:
  metal3-io/ironic-hardware-inventory-recorder-image:
  metal3-io/ironic-image:
  metal3-io/ironic-inspector-image:
  metal3-io/ironic-ipa-downloader:
  metal3-io/ironic-prometheus-exporter:
  metal3-io/metal3-dev-env:
  metal3-io/metal3-docs:
  metal3-io/metal3-helm-chart:
  metal3-io/metal3-io.github.io:
  metal3-io/metal3-smart-exporter:
  metal3-io/project-infra:
  - config-updater
  metal3-io/static-ip-manager-image:

config_updater:
  maps:
    prow/config/config.yaml:
      name: config
    prow/config/plugins.yaml:
      name: plugins
