apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prow
  namespace: prow
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
    sectionName: websecure
  hostnames:
  - "prow.apps.test.metal3.io"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: deck
      port: 80
      namespace: prow
      kind: Service
  - matches:
    - path:
        type: PathPrefix
        value: /hook
    backendRefs:
    - name: hook
      port: 8888
      namespace: prow
      kind: Service
