apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: prow
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      # <item-name>/[section-name/]<field-name>
      key: "prow-github-token/password"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hmac-token
  namespace: prow
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
  - secretKey: hmac
    remoteRef:
      # <item-name>/[section-name/]<field-name>
      key: "hmac-token/password"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-credentials
  namespace: prow
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
  - secretKey: service-account.json
    remoteRef:
      # <item-name>/[section-name/]<file-name>
      key: "s3-credentials/service-account.json"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cherrypick-bot-github-token
  namespace: prow
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      # <item-name>/[section-name/]<field-name>
      key: "prow-cherrypick-github-token/password"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-token
  namespace: prow
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      # <item-name>/[section-name/]<field-name>
      key: "prow-jenkins-token/password"
