presubmits:
  metal3-io/cluster-api-provider-metal3:
  - name: gomod
    branches:
    - main
    skip_if_only_changed: '(((^|/)OWNERS)|((^|/)OWNERS_ALIASES)|(\.md))$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/gomod.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/golang:1.24
        imagePullPolicy: Always
  # NOTE: The test jobs are for verifying Makefile and hack/* script changes only
  - name: test
    branches:
    - main
    run_if_changed: "^(Makefile|hack/.*)$"
    decorate: true
    spec:
      containers:
      - args:
        - test
        command:
        - make
        image: docker.io/golang:1.24
        imagePullPolicy: Always
  - name: markdownlint
    branches:
    - main
    run_if_changed: '(\.md|markdownlint\.sh)$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/markdownlint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/pipelinecomponents/markdownlint-cli2:0.12.0@sha256:a3977fba9814f10d33a1d69ae607dc808e7a6470b2ba03e84c17193c0791aac0
        imagePullPolicy: Always
  - name: shellcheck
    branches:
    - main
    run_if_changed: '((\.sh)|^Makefile)$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/shellcheck.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/koalaman/shellcheck-alpine:v0.10.0@sha256:5921d946dac740cbeec2fb1c898747b6105e585130cc7f0602eec9a10f7ddb63
        imagePullPolicy: Always
  - name: generate
    branches:
    - main
    skip_if_only_changed: '(((^|/)OWNERS)|((^|/)OWNERS_ALIASES)|(\.md))$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/codegen.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/golang:1.24
        imagePullPolicy: Always
  - name: unit
    branches:
    - main
    skip_if_only_changed: '(((^|/)OWNERS)|((^|/)OWNERS_ALIASES)|(\.md))$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/unit.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/golang:1.24
        imagePullPolicy: Always
  - name: manifestlint
    branches:
    - main
    skip_if_only_changed: '(((^|/)OWNERS)|((^|/)OWNERS_ALIASES)|(\.md))$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/manifestlint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        - name: KUBECONFORM_PATH
          value: "/"
        image: ghcr.io/yannh/kubeconform:v0.6.7-alpine@sha256:824e0c248809e4b2da2a768b16b107cf17ada88a89ec6aa6050e566ba93ebbc6
        imagePullPolicy: Always
  - name: build
    branches:
    - main
    run_if_changed: "^api|^test|^Makefile$|^hack/build.sh$"
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/build.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/golang:1.24
        imagePullPolicy: Always
  - name: build-fkas
    branches:
    - main
    run_if_changed: "^hack/fake-apiserver|^api|^Makefile$|^hack/build.sh$"
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/build.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        - name: BUILD_FKAS
          value: "TRUE"
        image: docker.io/golang:1.24
        imagePullPolicy: Always
  # name: {job_prefix}-{image_os}-e2e-basic-test-{capm3_target_branch}
  - name: metal3-centos-e2e-basic-test-main
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-basic-test-main
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  # name: {job_prefix}-{image_os}-e2e-integration-test-{capm3_target_branch}{suffix|} # suffix is optional
  - name: metal3-centos-e2e-integration-test-main
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: false
  - name: metal3-ubuntu-e2e-integration-test-main
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: false
  # name: {job_prefix}-{image_os}-e2e-integration-test-{capm3_target_branch}{suffix|} # suffix is optional
  - name: metal3-centos-e2e-integration-test-main-capi-nightly-build
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-integration-test-main-capi-nightly-build
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  # name: {job_prefix}-{image_os}-e2e-feature-test-{capm3_target_job}
  - name: metal3-centos-e2e-feature-test-main-pivoting
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-main-remediation
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-main-features
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-main-pivoting
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-main-remediation
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-main-features
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-main-scalability
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  # name: {job_prefix}-e2e-clusterctl-upgrade-test-{capm3_target_branch}
  - name: metal3-e2e-clusterctl-upgrade-test-main
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  # name: {job_prefix}-e2e-{k8s_versions}-upgrade-test-{capm3_target_branch}
  - name: metal3-e2e-1-33-1-34-upgrade-test-main
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  # name: {job_prefix}-{image_os}-e2e-kubernetes-n3-upgrade-{capm3_target_branch}
  - name: metal3-ubuntu-e2e-kubernetes-n3-upgrade-main
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-capi-md-test-main
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-capi-md-test-main
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  # name: {job_prefix}-e2e-conformance-test-{capm3_target_branch}
  - name: metal3-e2e-conformance-test-main
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  # name: {job_prefix}-{image_os}-e2e-integration-k8s-pre-release-test-{capm3_target_branch}
  - name: metal3-centos-e2e-integration-k8s-pre-release-test-main
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-integration-k8s-pre-release-test-main
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
