presubmits:
  metal3-io/project-infra:
  - name: check-prow-config
    skip_if_only_changed: '(((^|/)OWNERS)|((^|/)OWNERS_ALIASES)|(\.md))$'
    decorate: true
    spec:
      containers:
      - image: us-docker.pkg.dev/k8s-infra-prow/images/checkconfig:v20260126-ced54ae87
        command:
        - checkconfig
        args:
        - "--config-path"
        - "prow/config/config.yaml"
        - "--plugin-config"
        - "prow/config/plugins.yaml"
        - "--job-config-path"
        - "prow/config/jobs"
        - "--strict"
        resources:
          requests:
            memory: "500Mi"
  - name: markdownlint
    run_if_changed: '(\.md|markdownlint\.sh)$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/markdownlint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/pipelinecomponents/markdownlint-cli2:0.12.0@sha256:a3977fba9814f10d33a1d69ae607dc808e7a6470b2ba03e84c17193c0791aac0
        imagePullPolicy: Always
  - name: shellcheck
    run_if_changed: '((\.sh)|^Makefile)$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/shellcheck.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/koalaman/shellcheck-alpine:v0.10.0@sha256:5921d946dac740cbeec2fb1c898747b6105e585130cc7f0602eec9a10f7ddb63
        imagePullPolicy: Always
  - name: groovylint
    run_if_changed: '(\.groovy)$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/groovylint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/nvuillam/npm-groovy-lint:v16.1.1@sha256:fd8cf44d1ea3103f8f589770257f6f5960e76124c05a7fe81051bbff4dd3df38
        imagePullPolicy: Always
  - name: spellcheck
    run_if_changed: '(\.md|spellcheck\.sh|.cspell-config.json)$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/spellcheck.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: ghcr.io/streetsidesoftware/cspell:8.13.3@sha256:03df0e485775a43531c9c0e829227f39b3380796e92faab4166137dc5712d40a
        imagePullPolicy: Always
  - name: renovate-config-validator
    run_if_changed: '(renovate\.json|renovate-validator\.sh)$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/renovate-validator.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: docker.io/node:24-alpine
        imagePullPolicy: Always
  # name: {job_prefix}-{image_os}-e2e-basic-test-{capm3_target_branch}
  - name: metal3-centos-e2e-basic-test-main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-basic-test-release-1-11
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-basic-test-release-1-10
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-basic-test-main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-basic-test-release-1-11
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-basic-test-release-1-10
    agent: jenkins
    always_run: false
    optional: true
  # name: {job_prefix}-{image_os}-e2e-integration-test-{capm3_target_branch}
  - name: metal3-centos-e2e-integration-test-main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-integration-test-release-1-11
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-integration-test-release-1-10
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-integration-test-main
    agent: jenkins
    always_run: false
    optional: false
  - name: metal3-ubuntu-e2e-integration-test-release-1-11
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-integration-test-release-1-10
    agent: jenkins
    always_run: false
    optional: true
  # name: {job_prefix}-{image_os}-e2e-feature-test-{capm3_target_job}
  - name: metal3-centos-e2e-feature-test-main-pivoting
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-release-1-11-pivoting
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-release-1-10-pivoting
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-main-remediation
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-release-1-11-remediation
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-release-1-10-remediation
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-main-features
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-release-1-11-features
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-feature-test-release-1-10-features
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-main-pivoting
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-release-1-11-pivoting
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-release-1-10-pivoting
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-main-remediation
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-release-1-11-remediation
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-release-1-10-remediation
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-main-features
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-release-1-11-features
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-feature-test-release-1-10-features
    agent: jenkins
    always_run: false
    optional: true
  # name: {job_prefix}-e2e-clusterctl-upgrade-test-{capm3_target_branch}
  - name: metal3-e2e-clusterctl-upgrade-test-main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-e2e-clusterctl-upgrade-test-release-1-11
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-e2e-clusterctl-upgrade-test-release-1-10
    agent: jenkins
    always_run: false
    optional: true
  # name: {job_prefix}-e2e-{k8s_versions}-upgrade-test-{capm3_target_branch}
  - name: metal3-e2e-1-29-1-30-upgrade-test-main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-e2e-1-29-1-30-upgrade-test-release-1-11
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-e2e-1-29-1-30-upgrade-test-release-1-10
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-dev-env-integration-test-centos-main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-dev-env-integration-test-centos-release-1-11
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-dev-env-integration-test-centos-release-1-10
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-dev-env-integration-test-ubuntu-main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-dev-env-integration-test-ubuntu-release-1-11
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-dev-env-integration-test-ubuntu-release-1-10
    agent: jenkins
    always_run: false
    optional: true
  # name: {job_prefix}-bml-integration-test-{image_os}
  - name: metal3-bml-integration-test-centos
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-fullstack-build
    branches:
    - main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ci-image-building
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-node-image-building
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-capi-md-test-main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-centos-e2e-capi-md-test-main
    agent: jenkins
    always_run: false
    optional: true
  # name: {job_prefix}-e2e-conformance-test-{capm3_target_branch}
  - name: metal3-e2e-conformance-test-main
    agent: jenkins
    always_run: false
    optional: true
  # name: {job_prefix}-{image_os}-e2e-integration-k8s-pre-release-test-{capm3_target_branch}
  - name: metal3-centos-e2e-integration-k8s-pre-release-test-main
    agent: jenkins
    always_run: false
    optional: true
  - name: metal3-ubuntu-e2e-integration-k8s-pre-release-test-main
    agent: jenkins
    always_run: false
    optional: true
