apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/controlplaneio-fluxcd/flux-operator/releases/download/v0.40.0/install.yaml
- flux.yaml
- externalsecret.yaml
- github-dispatch-provider.yaml
- reconciliation-alert.yaml
- ../capi

patches:
# Add toleration and node selector to run on infra nodes
- path: toleration-node-selector-patch.yaml
  target:
    kind: Deployment
    name: flux-operator
    namespace: flux-system
