name: Groovy Lint Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    paths:
    - 'jenkins/jobs/**/*.groovy'

permissions: {}

jobs:
  groovy-lint-check:
    runs-on: ubuntu-latest
    container:
      image: nvuillam/npm-groovy-lint@sha256:60cf2ae84bfb5b112bc74352dba26f78e91790d30b2addb35fc4eab76bf93bd1 # v15.2.2
    steps:
    - name: Check out repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    - name: Run groovy linter
      run: npm-groovy-lint
