apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.28.0/manifests/controller-manager/cloud-controller-manager-roles.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.28.0/manifests/controller-manager/cloud-controller-manager-role-bindings.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.28.0/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.28.0/manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.28.0/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.28.0/manifests/cinder-csi-plugin/cinder-csi-nodeplugin-rbac.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.28.0/manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
- https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/v1.28.0/manifests/cinder-csi-plugin/csi-cinder-driver.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- files:
  - cloud.conf
  name: cloud-config
  namespace: kube-system
  type: Opaque
